//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceId { get; set; }
        public string CustomerId { get; set; }
        public string ManagerId { get; set; }
        public string PickupCity { get; set; }
        public string DropCity { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public bool ServiceStatus { get; set; }
        public double SericeCost { get; set; }
        public Nullable<int> ratings { get; set; }
        public string TruckNumber { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
