//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyTruck
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Truck
    {
        [Required(ErrorMessage = "Please Enter truck Number")]
        [MaxLength(10, ErrorMessage = "Please Enter Valid Truck  Number")]
        [MinLength(10, ErrorMessage = "Please Enter Valid Truck  Number")]
        [Remote("IsTuckExixts", "Manager", ErrorMessage = "Truck already exist")]
        [Display(Name = "Truck Number")]
        public string TruckNumber { get; set; }

        [Required(ErrorMessage = "Please Select truck Type")]
        [Display(Name = "Truck Type")]
        public string TruckType { get; set; }

        [Display(Name = "Manager Id")]
        public string ManagerId { get; set; }

        [Required(ErrorMessage = "Please Enter Driver Name")]
        [Display(Name = "Driver Name")]
        public string DriverName { get; set; }

        [Required(ErrorMessage = "Please Enter Driver Driving Licence")]
        [MaxLength(15, ErrorMessage = "Invalid Driving Licence Number")]
        [MinLength(15, ErrorMessage = "Invalid Driving Licence Number")]
        [Display(Name = "Driver Driving Licence")]
        public string DriverLicenceNumber { get; set; }

        [Required(ErrorMessage = "Please Select Pick up City")]
        [Display(Name = "Pick up City")]
        public string PickCity { get; set; }

        [Required(ErrorMessage = "Please Select Drop City")]
        [Display(Name = "Drop City")]
        public string DropCity { get; set; }

        [Required(ErrorMessage = "Please enter Maximum Capacity ")]
        [Display(Name = "Maximum Capacity in Ton's")]
        [RegularExpression("^[1-9]+(\\.\\d)?\\d*$", ErrorMessage = "Invalid Capacity ")]
        public double MaxCapacity { get; set; }

        [Required(ErrorMessage = "Please Enter Cost")]
        [Display(Name = "Minimum Cost")]
        [RegularExpression("^[1-9]+(\\.\\d)?\\d*$", ErrorMessage = "Invalid Cost ")]
        public double CostPerKM { get; set; }

        [Display(Name = "Add or Remove")]
        public bool TruckStatus { get; set; }

        [Display(Name = "Booking Status")]
        public bool BookedStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
